researcher_anthropic_task:
  description: >
    Conduct a thorough research about ticker symbol {name} using Anthropic's capabilities.
    Make sure you find any interesting and relevant information about the company, how it is performing, what are analysts saying about it.
    Make sure to add last 4 quater earnings results, analyst ratings, future price predictions, etc.
    Find news articles, blog posts, etc. that are relevant to the company and its stock market performance.
    Also make sure to find what could go wrong, what are the risks, etc.
    Also track last 2 month price movement, volume, volatility, and other technical indicators.
    Who all are the major shareholders, who all are the major institutional investors, who all are the major insiders, etc.
    the current year is {current_year}.
  expected_output: >
    A list with 40 bullet points of the most relevant information about ticker symbol {name}
  agent: researcher_anthropic

reporter_anthropic_task:
  description: >
    Review the context you got from researcher_anthropic_task and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  context:
    - researcher_anthropic_task
  markdown: true
  agent: reporter_anthropic

researcher_gemini_task:
  description: >
    Conduct a thorough research about ticker symbol {name} using Gemini's capabilities.
    Make sure you find any interesting and relevant information about the company, how it is performing, what are analysts saying about it.
    Make sure to add last 4 quater earnings results, analyst ratings, future price predictions, etc.
    Find news articles, blog posts, etc. that are relevant to the company and its stock market performance.
    Also make sure to find what could go wrong, what are the risks, etc.
    Also track last 2 month price movement, volume, volatility, and other technical indicators.
    Who all are the major shareholders, who all are the major institutional investors, who all are the major insiders, etc.
    the current year is {current_year}.
  expected_output: >
    A list with 40 bullet points of the most relevant information about ticker symbol {name}
  agent: researcher_gemini

reporter_gemini_task:
  description: >
    Review the context you got from researcher_gemini_task and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  context:
    - researcher_gemini_task
  markdown: true
  agent: reporter_gemini

researcher_openai_task:
  description: >
    Conduct a thorough research about ticker symbol {name} using OpenAI's capabilities.
    Make sure you find any interesting and relevant information about the company, how it is performing, what are analysts saying about it.
    Make sure to add last 4 quater earnings results, analyst ratings, future price predictions, etc.
    Find news articles, blog posts, etc. that are relevant to the company and its stock market performance.
    Also make sure to find what could go wrong, what are the risks, etc.
    Also track last 2 month price movement, volume, volatility, and other technical indicators.
    Who all are the major shareholders, who all are the major institutional investors, who all are the major insiders, etc.
    the current year is {current_year}.
  expected_output: >
    A list with 40 bullet points of the most relevant information about ticker symbol {name}
  agent: researcher_openai

reporter_openai_task:
  description: >
    Review the context you got from researcher_openai_task and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  context:
    - researcher_openai_task
  markdown: true
  agent: reporter_openai